services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    depends_on:
      - php
      - mysql
    container_name: laravel_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html
      - ./docker/nginx/ssl:/etc/nginx/ssl

  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    container_name: laravel_php
    volumes:
      - .:/var/www/html

  mysql:
    image: mariadb:latest
    platform: linux/amd64
    container_name: laravel_mysql
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  composer:
    image: composer:latest
    container_name: laravel_composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  artisan:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    container_name: laravel_artisan
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['php', 'artisan']

  npm:
    image: node:latest
    container_name: laravel_npm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']

volumes:
  mysql_data: